# Generated by Django 5.2.3 on 2025-07-03 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Apartment', 'Apartment'), ('Bedsitter', 'Bedsitter'), ('Single Room', 'Single Room'), ('Hostel', 'Hostel'), ('Bungalow', 'Bungalow'), ('Maisonette', 'Maisonette'), ('Studio', 'Studio'), ('Office', 'Office'), ('Villa', 'Villa'), ('Shop', 'Shop'), ('House', 'House')], max_length=50)),
                ('description', models.TextField()),
                ('size', models.PositiveIntegerField(help_text='Size in square meters or sqft')),
                ('beds', models.PositiveIntegerField(default=0)),
                ('baths', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], default='rent', max_length=10)),
                ('featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
