# Generated by Django 5.2.3 on 2025-07-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_property_is_booked_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy')], default='rent', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(default='Card', max_length=50),
        ),
    ]
