# Generated by Django 5.2.3 on 2025-07-04 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_notification_options_notification_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('months', models.JSONField()),
                ('cardNumber', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=5)),
                ('expiry', models.CharField(max_length=7)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
